#!/usr/bin/env python3
# -*- coding: utf-8 -*-:q

# 参考にしたサイト
# https://qiita.com/kzkadc/items/e4fc7bc9c003de1eb6d0
# https://note.nkmk.me/python-resas-api-download/

import os
import argparse
import json
import urllib.request
from collections import OrderedDict

# このプログラムの説明####################################
parser = argparse.ArgumentParser(description='webAPIからダウンロードしたデータをjsonファイルに格納するコマンドみたいなのを作りました')
# 引数を先に宣言しておく###################################
parser.add_argument('url')  # url
parser.add_argument('-f', '--file', default='a.json')  # jsonファイル名
# 引数を解析############################################
args = parser.parse_args()
# 同じ名前のファイルがあったら、エラーを出す###################
CurrentDirectori = os.getcwd()
files = os.listdir(CurrentDirectori)
files_file = [f for f in files if os.path.isfile(os.path.join(CurrentDirectori, f))]
JsonFileName = args.file
if JsonFileName in files_file:
    print('同じ名前のファイルが存在しています')
    exit(1)

#APIからデータをダウンロードしてくる########################
url = args.url
READ = urllib.request.urlopen(url)
response = READ.read()
data = json.loads(response, object_pairs_hook = OrderedDict)
#保存する###############################################
filename = CurrentDirectori + '/' + JsonFileName
with open(filename, 'w') as f:
    json.dump(data, f, ensure_ascii=False, indent=4)
